version: '3'

services:
  Bittrexdemo:
    image: bittrexdemo:latest
    build:
      context: .
      dockerfile: Dockerfil
    container_name: bittrexdemocontaine
    restart: "no"
    volumes:
      - "/home/niit/Music/sumeetcode/data:/home/user/data"
    ports:
     - "5000:5000"
